include_guard(GLOBAL)

cmcm_module(Colors.cmake LOCAL modules/Colors.cmake VERSION 1)
cmcm_module(Missives.cmake LOCAL modules/Missives.cmake VERSION 1)
cmcm_module(Standards.cmake LOCAL modules/Standards.cmake VERSION 1)
cmcm_module(PreventInSourceBuilds.cmake LOCAL modules/PreventInSourceBuilds.cmake VERSION 1)
cmcm_module(DefaultInstallPrefix.cmake LOCAL modules/DefaultInstallPrefix.cmake VERSION 1)
cmcm_module(Doctest.cmake LOCAL modules/Doctest.cmake VERSION 1)
cmcm_module(Testings.cmake LOCAL modules/Testings.cmake VERSION 1)
cmcm_module(CPM.cmake LOCAL modules/CPM.cmake VERSION 1)
cmcm_module(Ping.cmake LOCAL modules/Ping.cmake VERSION 1)
cmcm_module(Lcio.cmake LOCAL modules/Lcio.cmake VERSION 1)
cmcm_module(CLI11.cmake LOCAL modules/CLI11.cmake VERSION 1)
cmcm_module(Documentations.cmake LOCAL modules/Documentations.cmake VERSION 1)
cmcm_module(Zlib-ng.cmake LOCAL modules/Zlib-ng.cmake VERSION 1)
cmcm_module(Fmt.cmake LOCAL modules/Fmt.cmake VERSION 1)
cmcm_module(Spdlog.cmake LOCAL modules/Spdlog.cmake VERSION 1)
cmcm_module(Semver.cmake LOCAL modules/Semver.cmake VERSION 1)
cmcm_module(CMakeMicromamba.cmake LOCAL modules/CMakeMicromamba.cmake VERSION 1)
